name: Deployment
on:
  #push:
  #  branches:
  #    - main
  pull_request_review: 
    types: [submitted]
jobs:
  approved:
      if: github.event.review.state == 'APPROVED'
      runs-on: ubuntu-latest
      steps:
        - run: echo "This PR was approved"

    #lintelés
    #minden job használhat cachelést
    #saját workflowkat lehet használni
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test code
        run: echo "ez itt a teszteles"
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Build website
        run: echo "ez itt a buildelés"
      #- name: Upload artifacts
      #  uses: actions/upload-artifact@v3
      #  with:
      #      name: dist-files
      #      path: dist
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Check if the review was approved
        if: github.event.review.state == 'APPROVED'
        run: echo "a pull request jova hagyva"
      #- name: Get build artifacts
      #  uses: actions/download-artifact@v3
      #  with:
      #    name: dist-files
      #    path: ./dist
      - name: Output contents
        run: ls
      #- name: Deploy site
      #  id: deploy
      #  uses: ./.github/actions/deploy-s3-docker #a dockert le lehet cserélni javascript-re
      #  with:
      #    bucket: ps-teszt-hosting #ez a saját aws bucketem neve
      #    dist-folder: ./dist
          # bucket-region: eu-central-1
      - name: Upload to AWS S3
        #run: echo "itt lesz az aws feltoltes"
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete --exclude '.git*/*'
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}